name: .NET Prod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    environment: Production

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ secrets.APPSETTINGS_PATH }}
      env:
        ApplicationInsights.InstrumentationKey: ${{ secrets.APPLICATIONINSIGHTS_INSTRUMENTATIONKEY }}
        ConnectionStrings.Database: ${{ secrets.CONNECTIONSTRING_DATABASE }}
        Captcha.ValidationUrl: ${{ secrets.CAPTCHA_VALIDATION_URL }}
        Captcha.SiteKey: ${{ secrets.CAPTCHA_SITEKEY }}
        Captcha.SecretKey: ${{ secrets.CAPTCHA_SECRETKEY }}
        Microsoft.ClarityKey: ${{ secrets.MICROSOFT_CLARITY_KEY }}
        Plausible.Domain: ${{ secrets.PLAUSIBLE_DOMAIN }}
        Newsletter.Code: ${{ secrets.NEWSLETTER_CODE }}
        Newsletter.Url: ${{ secrets.NEWSLETTER_URL }}
        Umami.Id: ${{ secrets.UMAMI_ID }}
        Umami.Url: ${{ secrets.UMAMI_URL }}
    - name: dotnet publish
      run: dotnet publish -c Release --no-restore --no-build -p:PublishProfile=PTisp -p:Password=${{secrets.PUBLISH_PASSWORD}} -o ${{ secrets.PUBLISH_OUTPUT }}
