name: .NET dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-deploy:
    environment: DEV

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: dotnet publish
      run: dotnet publish -p:PublishProfile=FolderProfile
      
    # ftp deploy
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        # ftp server
        server: ${{ secrets.SERVER }}
        # ftp username
        username: ${{ secrets.USERNAME }}
        # ftp password
        password: ${{ secrets.PASSWORD }}
        # Folder to upload from, must end with trailing slash /
        local-dir: ./src/FabioCosta.Web/bin/Debug/net5.0/publish/
        # Path to upload to on the server. Must end with trailing slash /
        server-dir: ${{ secrets.SERVER_DIR }}
