name: CI

on: 
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Dotnet Publish
      run: dotnet publish -p:PublishProfile=FolderProfile

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP }}
        username: ${{ secrets.FTP_USER_DEV }}
        password: ${{ secrets.FTP_PASS_DEV }}
        local-dir: ${{ secrets.PUBLISH_PATH_DEV }}